name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: compile
      run: |
        cd TCP 
        gcc -o tcp main.c
        cd ..
    
    - name: compress
      run: tar -cvf .TCP/artifacts.tar ./TCP
      
    - name: see files
      run: ls -al
    
    - name: upload macOS binary
      uses: actions/upload-artifact@v2
      with:
        name: assets
        path: TCP

